# Generated by Django 5.0.2 on 2024-02-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='avater.png', null=True, upload_to=''),
        ),
    ]
