# Generated by Django 5.0.2 on 2024-02-18 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
    ]
