# Generated by Django 5.0.2 on 2024-02-18 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_remove_profile_profile_pic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('main_balance', models.CharField(max_length=200, null=True)),
                ('main_income', models.CharField(max_length=200, null=True)),
                ('main_expense', models.CharField(max_length=200, null=True)),
                ('crypto_balance', models.CharField(max_length=200, null=True)),
                ('crypto_income', models.CharField(max_length=200, null=True)),
                ('crypto_expense', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
