# Generated by Django 5.0.2 on 2024-02-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0013_pict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pict',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='card',
            name='profile_pic',
            field=models.ImageField(blank=True, default='avater.png', null=True, upload_to=''),
        ),
    ]
