# Generated by Django 5.0.2 on 2024-02-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0017_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='status',
            field=models.CharField(default='Pending', max_length=200, null=True),
        ),
    ]
