# Generated by Django 5.0.2 on 2024-02-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0021_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='pin',
            field=models.CharField(default='0000', max_length=200, null=True),
        ),
    ]
